# Generated by Django 4.1.2 on 2022-11-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_request_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in proqress', 'В процессе'), ('completed', 'Завершено')], default='new', max_length=254, verbose_name='Статус'),
        ),
    ]
