# Generated by Django 4.1.2 on 2022-11-16 16:34

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_request_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='photo',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=catalog.models.get_name_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp']), catalog.models.file_size], verbose_name='Фотография'),
        ),
    ]
