# Generated by Django 4.1.2 on 2022-11-22 15:27

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_request_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='photo_done',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to=catalog.models.get_name_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp']), catalog.models.file_size], verbose_name='Готовые работы'),
        ),
        migrations.AddField(
            model_name='request',
            name='text_commit',
            field=models.TextField(max_length=500, null=True, verbose_name='Комментарий'),
        ),
    ]
